print('We learn programing language Python')
print('I', 'am', 'learning', 'to', 'program', 'in', 'Python!')
print('1', '2', '4', '8', '16')
print('What a beautiful day!')
print("I'm not lazy to work!")
print('What a beautiful day!')
print()
print("I'm not lazy to work!")
print()
print('There are "double" quotes in the text')
print("There are 'single' quotes in the text")
print("I'm", 'the', "BAD", 'guy')
print("12 ' 34")